var car = "Toyota";
console.log("Is car == 'Toyota'? I preditc True.");
console.log(car == 'Toyota');
console.log("Is car == 'bmx'? I preditc it false");
console.log(car == 'bmx');
var banana = "fruit";
console.log(" Is banana == 'fruit' i preditc it true");
console.log(banana == 'fruit');
console.log(" Is banana == 'Vegetable'? i preditc it false");
console.log(banana == 'Vegetable');
var cabbage = "Vegetable";
console.log(" Is cabbage == 'Vegetable' i preditc it true");
console.log(cabbage == 'Vegetable');
console.log(" Is cabbage == 'fruit'? i preditc it false");
console.log(cabbage == 'fruit');
var table = "furniture";
console.log(" Is table == 'furniture' i preditc it true");
console.log(table == 'furniture');
console.log(" Is table == 'cloth'? i preditc it false");
console.log(table == 'cloth');
var frock = "clothes";
console.log(" Is frock == 'clothes' i preditc it true");
console.log(frock == 'clothes');
console.log(" Is frock == 'tree'? i preditc it false");
console.log(frock == 'tree');
